### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by jujuko75** [jujuko75/furima-30931#9]
**自身のフリマアプリのURL**
https://furima-30931.herokuapp.com/

**Basic認証のIDとパスワード**
id: admin
pass: 2222

**出品者用のメールアドレスとパスワード**
出品者名: test1
mail: sample@gmail.com
pass: 111111yy

**購入者用のメールアドレスとパスワード**
出品者名: test2
mail: sample2@gmail.com
pass: 111111yy

**購入用カードの番号・期限・セキュリティコード**
カード情報: 4242424242424242
期限: 3/24
セキュリティコード: 123

**Comment by kuroshio214** [comment]
jujuko75さん、ご提出ありがとうございます！

動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
商品商品詳細ページで、商品出品時に登録した情報の【発送元の地域情報】が表示されていません。
それ以外の情報は表示できているので、発送元の地域情報も表示されるように修正をお願いいたします。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by jujuko75** [comment]
ご指摘いただいた箇所、自身で確認しエラーを確認できませんでした。
ライフコーチへ相談し、メンターでご確認いただいた上、ライフコーチでご確認いただきましたが、エラー箇所が確認できませんでした。
再度報告フォーム送信しますので、よろしくお願いします。

**Comment by TECHCAMP555** [comment]
jujuko75 さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
